import Header from '@/components/Header/Header';
import { Raleway } from 'next/font/google';
import type { Metadata } from 'next';

import './globals.css';
import Footer from '@/components/Footer/Footer';

const raleway = Raleway({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      <body className={raleway.className}>
        <Header />
        <main className='py-[48px] px-[136px]'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
